# Generated by Django 3.2.3 on 2021-05-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbcontributor",
            name="email",
            field=models.CharField(help_text="The contributor's email address.", max_length=320, null=True),
        ),
    ]
